name: pipeline

# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: "Run Tests"
    strategy:
      matrix:
        php: [ '8.1.7', '8.5.4' ]

    runs-on: ubuntu-latest
    container: antriver/php:${{ matrix.php }}-cli

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: composer update --no-interaction --prefer-dist

      - name: Run tests
        run: composer test
